[phases.name]
  nixLibs = ['libheif']
  nixPkgs = ["tesseract", "tesseract5"]
[phases.build]
  cmds = ['pip uninstall opencv-python -y && pip uninstall opencv-python-headless -y && pip install opencv-python-headless']